---
- hosts: test
  connection: local
  become: yes
  
  vars:  
    server_name: "{{ ansible_default_ipv4.address }}"
    document_root: /opt/nginx/ansible
    app_root: edu-site
  
  tasks:
    - name: Обновить и установить Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
 
    - name: Установить PHP-FPM
      apt:
        name: php-fpm 
        state: latest
        update_cache: yes    

    - name: Скопировать содержимое сайта
      copy:
        src: "{{ app_root }}"
        dest: "{{ document_root }}"
        mode: preserve

    - name: Применить Nginx шаблон
      template:
        src: edu-config/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Restart Nginx

    - name: Запуск Nginx
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx

    - name: Открыть 80 порт
      ufw:
        rule: allow
        port: '80'
        proto: tcp

  handlers:
    - name: Пересчитывание конфигурации Nginx
      service:
        name: nginx
        state: restarted